### ISSUE TITLE
Long-Term Vision Statement

### ISSUE THREAD

**Issue by MCGitHub15** [MCGitHub15/Group-11-Project-Entrepreneurism-Ethics#1]
Create the following:
Long-Term Vision Statement - write in full paragraphs not bullets a statement that addresses each of the questions below.

- [x]  Goals: what are the goals?
- [x] Idea Origination: where did your idea come from ( a class, a job, a need)?
- [x] Purpose/Values/Mission: what is the purpose, values, and mission?
- [x] Key Questions: List 2 or 3 key questions that will guide the startup's choices. These should be essential questions that serve as touchstones to direct your company's efforts. For instance, how can the startup have an impact? What engages our passions?

**Comment by hasibayoubi** [comment]
Completed Goals, Idea Origination, Purpose/Values/Mission and Key Questions.

**Comment by MCGitHub15** [comment]
Looks goods. Thanks Hasib.
