### ISSUE TITLE
Pt2 Cultural Policy: Core Values

### ISSUE THREAD

**Issue by MCGitHub15** [MCGitHub15/Group-11-Project-Entrepreneurism-Ethics#5]
- [ ]  Give core values of the company answering questions: How do you want to be thought of? What are the details of the core values of the company? (write in full paragraphs not bullets)

**Comment by hasibayoubi** [comment]
Completed the core values. @MCGitHub15 you may want to review it and see if anything is missing or if you want to add anything to it you are welcome to do so.
